title: XV2 Wiki
baseurl: ""
url: ""
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty
exclude:
  - assets
  - data
  - '*.json'
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: wiki
